// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using covid19tracker.Model;

namespace covid19tracker.Migrations.WorldAggregated
{
    [DbContext(typeof(WorldAggregatedContext))]
    partial class WorldAggregatedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("covid19tracker.Model.WorldAggregated", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Confirmed")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<float?>("IncreaseRate")
                        .HasColumnType("real");

                    b.Property<int>("Recovered")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.ToTable("WorldData");

                    b.HasData(
                        new
                        {
                            Date = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 555,
                            Deaths = 17,
                            Recovered = 28
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 654,
                            Deaths = 18,
                            IncreaseRate = 17.837837f,
                            Recovered = 30
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 941,
                            Deaths = 26,
                            IncreaseRate = 43.883793f,
                            Recovered = 36
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1434,
                            Deaths = 42,
                            IncreaseRate = 52.391075f,
                            Recovered = 39
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 2118,
                            Deaths = 56,
                            IncreaseRate = 47.698746f,
                            Recovered = 52
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 2927,
                            Deaths = 82,
                            IncreaseRate = 38.19641f,
                            Recovered = 61
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 5578,
                            Deaths = 131,
                            IncreaseRate = 90.57055f,
                            Recovered = 107
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 6166,
                            Deaths = 133,
                            IncreaseRate = 10.541412f,
                            Recovered = 126
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 8234,
                            Deaths = 171,
                            IncreaseRate = 33.53876f,
                            Recovered = 143
                        },
                        new
                        {
                            Date = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 9927,
                            Deaths = 213,
                            IncreaseRate = 20.561089f,
                            Recovered = 222
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 12038,
                            Deaths = 259,
                            IncreaseRate = 21.265236f,
                            Recovered = 284
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 16787,
                            Deaths = 362,
                            IncreaseRate = 39.450073f,
                            Recovered = 472
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 19881,
                            Deaths = 426,
                            IncreaseRate = 18.43093f,
                            Recovered = 623
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 23892,
                            Deaths = 492,
                            IncreaseRate = 20.175041f,
                            Recovered = 852
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 27635,
                            Deaths = 564,
                            IncreaseRate = 15.666332f,
                            Recovered = 1124
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 30794,
                            Deaths = 634,
                            IncreaseRate = 11.431156f,
                            Recovered = 1487
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 34391,
                            Deaths = 719,
                            IncreaseRate = 11.680847f,
                            Recovered = 2011
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 37120,
                            Deaths = 806,
                            IncreaseRate = 7.9352155f,
                            Recovered = 2616
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 40150,
                            Deaths = 906,
                            IncreaseRate = 8.162716f,
                            Recovered = 3244
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 42762,
                            Deaths = 1013,
                            IncreaseRate = 6.505604f,
                            Recovered = 3946
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 44802,
                            Deaths = 1113,
                            IncreaseRate = 4.770591f,
                            Recovered = 4683
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 45221,
                            Deaths = 1118,
                            IncreaseRate = 0.9352261f,
                            Recovered = 5150
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 60368,
                            Deaths = 1371,
                            IncreaseRate = 33.4955f,
                            Recovered = 6295
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 66885,
                            Deaths = 1523,
                            IncreaseRate = 10.795455f,
                            Recovered = 8058
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 69030,
                            Deaths = 1666,
                            IncreaseRate = 3.2069972f,
                            Recovered = 9395
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 71224,
                            Deaths = 1770,
                            IncreaseRate = 3.1783283f,
                            Recovered = 10865
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 73258,
                            Deaths = 1868,
                            IncreaseRate = 2.855779f,
                            Recovered = 12583
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 75136,
                            Deaths = 2007,
                            IncreaseRate = 2.5635426f,
                            Recovered = 14352
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 75639,
                            Deaths = 2122,
                            IncreaseRate = 0.6694527f,
                            Recovered = 16121
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 76197,
                            Deaths = 2247,
                            IncreaseRate = 0.73771465f,
                            Recovered = 18177
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 76819,
                            Deaths = 2251,
                            IncreaseRate = 0.8163051f,
                            Recovered = 18890
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 78572,
                            Deaths = 2458,
                            IncreaseRate = 2.2819874f,
                            Recovered = 22886
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 78958,
                            Deaths = 2469,
                            IncreaseRate = 0.49126914f,
                            Recovered = 23394
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 79561,
                            Deaths = 2629,
                            IncreaseRate = 0.76369715f,
                            Recovered = 25227
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 80406,
                            Deaths = 2708,
                            IncreaseRate = 1.0620781f,
                            Recovered = 27905
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 81388,
                            Deaths = 2770,
                            IncreaseRate = 1.2213019f,
                            Recovered = 30384
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 82746,
                            Deaths = 2814,
                            IncreaseRate = 1.6685506f,
                            Recovered = 33277
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 84112,
                            Deaths = 2872,
                            IncreaseRate = 1.650835f,
                            Recovered = 36711
                        },
                        new
                        {
                            Date = new DateTime(2020, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 86011,
                            Deaths = 2941,
                            IncreaseRate = 2.257704f,
                            Recovered = 39782
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 88369,
                            Deaths = 2996,
                            IncreaseRate = 2.74151f,
                            Recovered = 42716
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 90306,
                            Deaths = 3085,
                            IncreaseRate = 2.191945f,
                            Recovered = 45602
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 92840,
                            Deaths = 3160,
                            IncreaseRate = 2.806015f,
                            Recovered = 48228
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 95120,
                            Deaths = 3254,
                            IncreaseRate = 2.455838f,
                            Recovered = 51170
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 97886,
                            Deaths = 3348,
                            IncreaseRate = 2.9079058f,
                            Recovered = 53796
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 101801,
                            Deaths = 3460,
                            IncreaseRate = 3.9995506f,
                            Recovered = 55865
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 105847,
                            Deaths = 3558,
                            IncreaseRate = 3.9744208f,
                            Recovered = 58358
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 109821,
                            Deaths = 3802,
                            IncreaseRate = 3.7544758f,
                            Recovered = 60694
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 113590,
                            Deaths = 3988,
                            IncreaseRate = 3.4319484f,
                            Recovered = 62494
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 118620,
                            Deaths = 4262,
                            IncreaseRate = 4.428207f,
                            Recovered = 64404
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 125875,
                            Deaths = 4615,
                            IncreaseRate = 6.1161695f,
                            Recovered = 67003
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 128352,
                            Deaths = 4720,
                            IncreaseRate = 1.9678252f,
                            Recovered = 68324
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 145205,
                            Deaths = 5404,
                            IncreaseRate = 13.130298f,
                            Recovered = 70251
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 156101,
                            Deaths = 5819,
                            IncreaseRate = 7.503874f,
                            Recovered = 72624
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 167454,
                            Deaths = 6440,
                            IncreaseRate = 7.2728553f,
                            Recovered = 76034
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 181574,
                            Deaths = 7126,
                            IncreaseRate = 8.432166f,
                            Recovered = 78088
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 197102,
                            Deaths = 7905,
                            IncreaseRate = 8.551886f,
                            Recovered = 80840
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 214821,
                            Deaths = 8733,
                            IncreaseRate = 8.989761f,
                            Recovered = 83312
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 242570,
                            Deaths = 9867,
                            IncreaseRate = 12.917266f,
                            Recovered = 84975
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 272208,
                            Deaths = 11299,
                            IncreaseRate = 12.218328f,
                            Recovered = 87420
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 304507,
                            Deaths = 12973,
                            IncreaseRate = 11.865559f,
                            Recovered = 91692
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 336953,
                            Deaths = 14651,
                            IncreaseRate = 10.655256f,
                            Recovered = 97899
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 378231,
                            Deaths = 16505,
                            IncreaseRate = 12.250373f,
                            Recovered = 98351
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 418041,
                            Deaths = 18625,
                            IncreaseRate = 10.525314f,
                            Recovered = 108000
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 467653,
                            Deaths = 21181,
                            IncreaseRate = 11.867736f,
                            Recovered = 113787
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 529591,
                            Deaths = 23970,
                            IncreaseRate = 13.244435f,
                            Recovered = 122150
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 593291,
                            Deaths = 27198,
                            IncreaseRate = 12.02815f,
                            Recovered = 130915
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 660693,
                            Deaths = 30652,
                            IncreaseRate = 11.360698f,
                            Recovered = 139415
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 720140,
                            Deaths = 33925,
                            IncreaseRate = 8.997674f,
                            Recovered = 149082
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 782389,
                            Deaths = 37582,
                            IncreaseRate = 8.644013f,
                            Recovered = 164566
                        },
                        new
                        {
                            Date = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 857487,
                            Deaths = 42107,
                            IncreaseRate = 9.59855f,
                            Recovered = 178034
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 932605,
                            Deaths = 47180,
                            IncreaseRate = 8.760249f,
                            Recovered = 193177
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1013466,
                            Deaths = 52983,
                            IncreaseRate = 8.6704445f,
                            Recovered = 210263
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1095917,
                            Deaths = 58787,
                            IncreaseRate = 8.135547f,
                            Recovered = 225796
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1176060,
                            Deaths = 64606,
                            IncreaseRate = 7.3128715f,
                            Recovered = 246152
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1249754,
                            Deaths = 69374,
                            IncreaseRate = 6.2661767f,
                            Recovered = 260012
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1321481,
                            Deaths = 74565,
                            IncreaseRate = 5.7392893f,
                            Recovered = 276515
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1396476,
                            Deaths = 81937,
                            IncreaseRate = 5.675072f,
                            Recovered = 300054
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1480202,
                            Deaths = 88338,
                            IncreaseRate = 5.99552f,
                            Recovered = 328661
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1565278,
                            Deaths = 95521,
                            IncreaseRate = 5.747594f,
                            Recovered = 353975
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1657526,
                            Deaths = 102525,
                            IncreaseRate = 5.893394f,
                            Recovered = 376096
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1735650,
                            Deaths = 108502,
                            IncreaseRate = 4.7132897f,
                            Recovered = 402110
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1834721,
                            Deaths = 114090,
                            IncreaseRate = 5.7080054f,
                            Recovered = 421722
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1904838,
                            Deaths = 119481,
                            IncreaseRate = 3.821671f,
                            Recovered = 448655
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 1976191,
                            Deaths = 125983,
                            IncreaseRate = 3.7458827f,
                            Recovered = 474261
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 2056054,
                            Deaths = 134176,
                            IncreaseRate = 4.0412593f,
                            Recovered = 511019
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 2152437,
                            Deaths = 143800,
                            IncreaseRate = 4.687766f,
                            Recovered = 542107
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 2240190,
                            Deaths = 153821,
                            IncreaseRate = 4.076914f,
                            Recovered = 568343
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 2317758,
                            Deaths = 159509,
                            IncreaseRate = 3.4625635f,
                            Recovered = 592319
                        },
                        new
                        {
                            Date = new DateTime(2020, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Confirmed = 2401378,
                            Deaths = 165043,
                            IncreaseRate = 3.607797f,
                            Recovered = 623903
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
