// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using covid19tracker.Model;

namespace covid19tracker.Migrations.ApiKey
{
    [DbContext(typeof(ApiKeyContext))]
    [Migration("20200521110632_ApiKeyInitialCreate")]
    partial class ApiKeyInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("covid19tracker.Model.ApiKey", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("ApiKeys");

                    b.HasData(
                        new
                        {
                            Key = new Guid("68103797-356b-4a52-9c08-09dedccd3efe"),
                            Created = new DateTime(2020, 5, 21, 11, 6, 32, 542, DateTimeKind.Utc).AddTicks(1275),
                            Expiration = new DateTime(2022, 5, 21, 11, 6, 32, 542, DateTimeKind.Utc).AddTicks(1587),
                            Owner = "mobile app",
                            Roles = "WorldData,CountryData,News"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
