// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using covid19tracker.Model;

namespace covid19tracker.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20200419104748_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("covid19tracker.Model.Country", b =>
                {
                    b.Property<string>("Iso2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Iso3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<float>("Long")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Iso2");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Iso2 = "AF",
                            Iso3 = "AFG",
                            Lat = 33.93911f,
                            Long = 67.70995f,
                            Name = "Afghanistan",
                            Population = 38928341
                        },
                        new
                        {
                            Iso2 = "AL",
                            Iso3 = "ALB",
                            Lat = 41.1533f,
                            Long = 20.1683f,
                            Name = "Albania",
                            Population = 2877800
                        },
                        new
                        {
                            Iso2 = "DZ",
                            Iso3 = "DZA",
                            Lat = 28.0339f,
                            Long = 1.6596f,
                            Name = "Algeria",
                            Population = 43851043
                        },
                        new
                        {
                            Iso2 = "AD",
                            Iso3 = "AND",
                            Lat = 42.5063f,
                            Long = 1.5218f,
                            Name = "Andorra",
                            Population = 77265
                        },
                        new
                        {
                            Iso2 = "AO",
                            Iso3 = "AGO",
                            Lat = -11.2027f,
                            Long = 17.8739f,
                            Name = "Angola",
                            Population = 32866268
                        },
                        new
                        {
                            Iso2 = "AG",
                            Iso3 = "ATG",
                            Lat = 17.0608f,
                            Long = -61.7964f,
                            Name = "Antigua and Barbuda",
                            Population = 97928
                        },
                        new
                        {
                            Iso2 = "AR",
                            Iso3 = "ARG",
                            Lat = -38.4161f,
                            Long = -63.6167f,
                            Name = "Argentina",
                            Population = 45195777
                        },
                        new
                        {
                            Iso2 = "AM",
                            Iso3 = "ARM",
                            Lat = 40.0691f,
                            Long = 45.0382f,
                            Name = "Armenia",
                            Population = 2963234
                        },
                        new
                        {
                            Iso2 = "AT",
                            Iso3 = "AUT",
                            Lat = 47.5162f,
                            Long = 14.5501f,
                            Name = "Austria",
                            Population = 9006400
                        },
                        new
                        {
                            Iso2 = "AZ",
                            Iso3 = "AZE",
                            Lat = 40.1431f,
                            Long = 47.5769f,
                            Name = "Azerbaijan",
                            Population = 10139175
                        },
                        new
                        {
                            Iso2 = "BS",
                            Iso3 = "BHS",
                            Lat = 25.025885f,
                            Long = -78.03589f,
                            Name = "Bahamas",
                            Population = 393248
                        },
                        new
                        {
                            Iso2 = "BH",
                            Iso3 = "BHR",
                            Lat = 26.0275f,
                            Long = 50.55f,
                            Name = "Bahrain",
                            Population = 1701583
                        },
                        new
                        {
                            Iso2 = "BD",
                            Iso3 = "BGD",
                            Lat = 23.685f,
                            Long = 90.3563f,
                            Name = "Bangladesh",
                            Population = 164689383
                        },
                        new
                        {
                            Iso2 = "BB",
                            Iso3 = "BRB",
                            Lat = 13.1939f,
                            Long = -59.5432f,
                            Name = "Barbados",
                            Population = 287371
                        },
                        new
                        {
                            Iso2 = "BY",
                            Iso3 = "BLR",
                            Lat = 53.7098f,
                            Long = 27.9534f,
                            Name = "Belarus",
                            Population = 9449321
                        },
                        new
                        {
                            Iso2 = "BE",
                            Iso3 = "BEL",
                            Lat = 50.8333f,
                            Long = 4.469936f,
                            Name = "Belgium",
                            Population = 11589616
                        },
                        new
                        {
                            Iso2 = "BZ",
                            Iso3 = "BLZ",
                            Lat = 17.1899f,
                            Long = -88.4976f,
                            Name = "Belize",
                            Population = 397621
                        },
                        new
                        {
                            Iso2 = "BJ",
                            Iso3 = "BEN",
                            Lat = 9.3077f,
                            Long = 2.3158f,
                            Name = "Benin",
                            Population = 12123198
                        },
                        new
                        {
                            Iso2 = "BT",
                            Iso3 = "BTN",
                            Lat = 27.5142f,
                            Long = 90.4336f,
                            Name = "Bhutan",
                            Population = 771612
                        },
                        new
                        {
                            Iso2 = "BO",
                            Iso3 = "BOL",
                            Lat = -16.2902f,
                            Long = -63.5887f,
                            Name = "Bolivia",
                            Population = 11673029
                        },
                        new
                        {
                            Iso2 = "BA",
                            Iso3 = "BIH",
                            Lat = 43.9159f,
                            Long = 17.6791f,
                            Name = "Bosnia and Herzegovina",
                            Population = 3280815
                        },
                        new
                        {
                            Iso2 = "BW",
                            Iso3 = "BWA",
                            Lat = -22.3285f,
                            Long = 24.6849f,
                            Name = "Botswana",
                            Population = 2351625
                        },
                        new
                        {
                            Iso2 = "BR",
                            Iso3 = "BRA",
                            Lat = -14.235f,
                            Long = -51.9253f,
                            Name = "Brazil",
                            Population = 212559409
                        },
                        new
                        {
                            Iso2 = "BN",
                            Iso3 = "BRN",
                            Lat = 4.5353f,
                            Long = 114.7277f,
                            Name = "Brunei",
                            Population = 437483
                        },
                        new
                        {
                            Iso2 = "BG",
                            Iso3 = "BGR",
                            Lat = 42.7339f,
                            Long = 25.4858f,
                            Name = "Bulgaria",
                            Population = 6948445
                        },
                        new
                        {
                            Iso2 = "BF",
                            Iso3 = "BFA",
                            Lat = 12.2383f,
                            Long = -1.5616f,
                            Name = "Burkina Faso",
                            Population = 20903278
                        },
                        new
                        {
                            Iso2 = "MM",
                            Iso3 = "MMR",
                            Lat = 21.9162f,
                            Long = 95.956f,
                            Name = "Burma",
                            Population = 54409794
                        },
                        new
                        {
                            Iso2 = "BI",
                            Iso3 = "BDI",
                            Lat = -3.3731f,
                            Long = 29.9189f,
                            Name = "Burundi",
                            Population = 11890781
                        },
                        new
                        {
                            Iso2 = "CV",
                            Iso3 = "CPV",
                            Lat = 16.5388f,
                            Long = -23.0418f,
                            Name = "Cabo Verde",
                            Population = 555988
                        },
                        new
                        {
                            Iso2 = "KH",
                            Iso3 = "KHM",
                            Lat = 11.55f,
                            Long = 104.9167f,
                            Name = "Cambodia",
                            Population = 16718971
                        },
                        new
                        {
                            Iso2 = "CM",
                            Iso3 = "CMR",
                            Lat = 3.848f,
                            Long = 11.5021f,
                            Name = "Cameroon",
                            Population = 26545864
                        },
                        new
                        {
                            Iso2 = "CF",
                            Iso3 = "CAF",
                            Lat = 6.6111f,
                            Long = 20.9394f,
                            Name = "Central African Republic",
                            Population = 4829764
                        },
                        new
                        {
                            Iso2 = "TD",
                            Iso3 = "TCD",
                            Lat = 15.4542f,
                            Long = 18.7322f,
                            Name = "Chad",
                            Population = 16425859
                        },
                        new
                        {
                            Iso2 = "CL",
                            Iso3 = "CHL",
                            Lat = -35.6751f,
                            Long = -71.543f,
                            Name = "Chile",
                            Population = 19116209
                        },
                        new
                        {
                            Iso2 = "CO",
                            Iso3 = "COL",
                            Lat = 4.5709f,
                            Long = -74.2973f,
                            Name = "Colombia",
                            Population = 50882884
                        },
                        new
                        {
                            Iso2 = "CG",
                            Iso3 = "COG",
                            Lat = -4.2634f,
                            Long = 15.2832f,
                            Name = "Congo (Brazzaville)",
                            Population = 5518092
                        },
                        new
                        {
                            Iso2 = "CD",
                            Iso3 = "COD",
                            Lat = -4.322447f,
                            Long = 15.307045f,
                            Name = "Congo (Kinshasa)",
                            Population = 89561404
                        },
                        new
                        {
                            Iso2 = "CR",
                            Iso3 = "CRI",
                            Lat = 9.7489f,
                            Long = -83.7534f,
                            Name = "Costa Rica",
                            Population = 5094114
                        },
                        new
                        {
                            Iso2 = "CI",
                            Iso3 = "CIV",
                            Lat = 7.54f,
                            Long = -5.5471f,
                            Name = "Cote d'Ivoire",
                            Population = 26378275
                        },
                        new
                        {
                            Iso2 = "HR",
                            Iso3 = "HRV",
                            Lat = 45.1f,
                            Long = 15.2f,
                            Name = "Croatia",
                            Population = 4105268
                        },
                        new
                        {
                            Iso2 = "CU",
                            Iso3 = "CUB",
                            Lat = 21.521757f,
                            Long = -77.781166f,
                            Name = "Cuba",
                            Population = 11326616
                        },
                        new
                        {
                            Iso2 = "CY",
                            Iso3 = "CYP",
                            Lat = 35.1264f,
                            Long = 33.4299f,
                            Name = "Cyprus",
                            Population = 1207361
                        },
                        new
                        {
                            Iso2 = "CZ",
                            Iso3 = "CZE",
                            Lat = 49.8175f,
                            Long = 15.473f,
                            Name = "Czechia",
                            Population = 10708982
                        },
                        new
                        {
                            Iso2 = "DK",
                            Iso3 = "DNK",
                            Lat = 56.2639f,
                            Long = 9.5018f,
                            Name = "Denmark",
                            Population = 5792203
                        },
                        new
                        {
                            Iso2 = "DJ",
                            Iso3 = "DJI",
                            Lat = 11.8251f,
                            Long = 42.5903f,
                            Name = "Djibouti",
                            Population = 988002
                        },
                        new
                        {
                            Iso2 = "DM",
                            Iso3 = "DMA",
                            Lat = 15.415f,
                            Long = -61.371f,
                            Name = "Dominica",
                            Population = 71991
                        },
                        new
                        {
                            Iso2 = "DO",
                            Iso3 = "DOM",
                            Lat = 18.7357f,
                            Long = -70.1627f,
                            Name = "Dominican Republic",
                            Population = 10847904
                        },
                        new
                        {
                            Iso2 = "EC",
                            Iso3 = "ECU",
                            Lat = -1.8312f,
                            Long = -78.1834f,
                            Name = "Ecuador",
                            Population = 17643060
                        },
                        new
                        {
                            Iso2 = "EG",
                            Iso3 = "EGY",
                            Lat = 26.820553f,
                            Long = 30.802498f,
                            Name = "Egypt",
                            Population = 102334403
                        },
                        new
                        {
                            Iso2 = "SV",
                            Iso3 = "SLV",
                            Lat = 13.7942f,
                            Long = -88.8965f,
                            Name = "El Salvador",
                            Population = 6486201
                        },
                        new
                        {
                            Iso2 = "GQ",
                            Iso3 = "GNQ",
                            Lat = 1.6508f,
                            Long = 10.2679f,
                            Name = "Equatorial Guinea",
                            Population = 1402985
                        },
                        new
                        {
                            Iso2 = "ER",
                            Iso3 = "ERI",
                            Lat = 15.1794f,
                            Long = 39.7823f,
                            Name = "Eritrea",
                            Population = 3546427
                        },
                        new
                        {
                            Iso2 = "EE",
                            Iso3 = "EST",
                            Lat = 58.5953f,
                            Long = 25.0136f,
                            Name = "Estonia",
                            Population = 1326539
                        },
                        new
                        {
                            Iso2 = "SZ",
                            Iso3 = "SWZ",
                            Lat = -26.5225f,
                            Long = 31.4659f,
                            Name = "Eswatini",
                            Population = 1160164
                        },
                        new
                        {
                            Iso2 = "ET",
                            Iso3 = "ETH",
                            Lat = 9.145f,
                            Long = 40.4897f,
                            Name = "Ethiopia",
                            Population = 114963583
                        },
                        new
                        {
                            Iso2 = "FJ",
                            Iso3 = "FJI",
                            Lat = -17.7134f,
                            Long = 178.065f,
                            Name = "Fiji",
                            Population = 896444
                        },
                        new
                        {
                            Iso2 = "FI",
                            Iso3 = "FIN",
                            Lat = 61.92411f,
                            Long = 25.748152f,
                            Name = "Finland",
                            Population = 5540718
                        },
                        new
                        {
                            Iso2 = "FR",
                            Iso3 = "FRA",
                            Lat = 46.2276f,
                            Long = 2.2137f,
                            Name = "France",
                            Population = 65273512
                        },
                        new
                        {
                            Iso2 = "GA",
                            Iso3 = "GAB",
                            Lat = -0.8037f,
                            Long = 11.6094f,
                            Name = "Gabon",
                            Population = 2225728
                        },
                        new
                        {
                            Iso2 = "GM",
                            Iso3 = "GMB",
                            Lat = 13.4432f,
                            Long = -15.3101f,
                            Name = "Gambia",
                            Population = 2416664
                        },
                        new
                        {
                            Iso2 = "GE",
                            Iso3 = "GEO",
                            Lat = 42.3154f,
                            Long = 43.3569f,
                            Name = "Georgia",
                            Population = 3989175
                        },
                        new
                        {
                            Iso2 = "DE",
                            Iso3 = "DEU",
                            Lat = 51.16569f,
                            Long = 10.451526f,
                            Name = "Germany",
                            Population = 83783945
                        },
                        new
                        {
                            Iso2 = "GH",
                            Iso3 = "GHA",
                            Lat = 7.9465f,
                            Long = -1.0232f,
                            Name = "Ghana",
                            Population = 31072945
                        },
                        new
                        {
                            Iso2 = "GR",
                            Iso3 = "GRC",
                            Lat = 39.0742f,
                            Long = 21.8243f,
                            Name = "Greece",
                            Population = 10423056
                        },
                        new
                        {
                            Iso2 = "GD",
                            Iso3 = "GRD",
                            Lat = 12.1165f,
                            Long = -61.679f,
                            Name = "Grenada",
                            Population = 112519
                        },
                        new
                        {
                            Iso2 = "GT",
                            Iso3 = "GTM",
                            Lat = 15.7835f,
                            Long = -90.2308f,
                            Name = "Guatemala",
                            Population = 17915567
                        },
                        new
                        {
                            Iso2 = "GN",
                            Iso3 = "GIN",
                            Lat = 9.9456f,
                            Long = -9.6966f,
                            Name = "Guinea",
                            Population = 13132792
                        },
                        new
                        {
                            Iso2 = "GW",
                            Iso3 = "GNB",
                            Lat = 11.8037f,
                            Long = -15.1804f,
                            Name = "Guinea-Bissau",
                            Population = 1967998
                        },
                        new
                        {
                            Iso2 = "GY",
                            Iso3 = "GUY",
                            Lat = 4.860416f,
                            Long = -58.93018f,
                            Name = "Guyana",
                            Population = 786559
                        },
                        new
                        {
                            Iso2 = "HT",
                            Iso3 = "HTI",
                            Lat = 18.9712f,
                            Long = -72.2852f,
                            Name = "Haiti",
                            Population = 11402533
                        },
                        new
                        {
                            Iso2 = "VA",
                            Iso3 = "VAT",
                            Lat = 41.9029f,
                            Long = 12.4534f,
                            Name = "Holy See",
                            Population = 809
                        },
                        new
                        {
                            Iso2 = "HN",
                            Iso3 = "HND",
                            Lat = 15.2f,
                            Long = -86.2419f,
                            Name = "Honduras",
                            Population = 9904608
                        },
                        new
                        {
                            Iso2 = "HU",
                            Iso3 = "HUN",
                            Lat = 47.1625f,
                            Long = 19.5033f,
                            Name = "Hungary",
                            Population = 9660350
                        },
                        new
                        {
                            Iso2 = "IS",
                            Iso3 = "ISL",
                            Lat = 64.9631f,
                            Long = -19.0208f,
                            Name = "Iceland",
                            Population = 341250
                        },
                        new
                        {
                            Iso2 = "IN",
                            Iso3 = "IND",
                            Lat = 20.593683f,
                            Long = 78.96288f,
                            Name = "India",
                            Population = 1380004385
                        },
                        new
                        {
                            Iso2 = "ID",
                            Iso3 = "IDN",
                            Lat = -0.7893f,
                            Long = 113.9213f,
                            Name = "Indonesia",
                            Population = 273523621
                        },
                        new
                        {
                            Iso2 = "IR",
                            Iso3 = "IRN",
                            Lat = 32.42791f,
                            Long = 53.688046f,
                            Name = "Iran",
                            Population = 83992953
                        },
                        new
                        {
                            Iso2 = "IQ",
                            Iso3 = "IRQ",
                            Lat = 33.22319f,
                            Long = 43.67929f,
                            Name = "Iraq",
                            Population = 40222503
                        },
                        new
                        {
                            Iso2 = "IE",
                            Iso3 = "IRL",
                            Lat = 53.1424f,
                            Long = -7.6921f,
                            Name = "Ireland",
                            Population = 4937796
                        },
                        new
                        {
                            Iso2 = "IL",
                            Iso3 = "ISR",
                            Lat = 31.046051f,
                            Long = 34.851612f,
                            Name = "Israel",
                            Population = 8655541
                        },
                        new
                        {
                            Iso2 = "IT",
                            Iso3 = "ITA",
                            Lat = 41.87194f,
                            Long = 12.56738f,
                            Name = "Italy",
                            Population = 60461828
                        },
                        new
                        {
                            Iso2 = "JM",
                            Iso3 = "JAM",
                            Lat = 18.1096f,
                            Long = -77.2975f,
                            Name = "Jamaica",
                            Population = 2961161
                        },
                        new
                        {
                            Iso2 = "JP",
                            Iso3 = "JPN",
                            Lat = 36.204823f,
                            Long = 138.25293f,
                            Name = "Japan",
                            Population = 126476458
                        },
                        new
                        {
                            Iso2 = "JO",
                            Iso3 = "JOR",
                            Lat = 31.24f,
                            Long = 36.51f,
                            Name = "Jordan",
                            Population = 10203140
                        },
                        new
                        {
                            Iso2 = "KZ",
                            Iso3 = "KAZ",
                            Lat = 48.0196f,
                            Long = 66.9237f,
                            Name = "Kazakhstan",
                            Population = 18776707
                        },
                        new
                        {
                            Iso2 = "KE",
                            Iso3 = "KEN",
                            Lat = -0.0236f,
                            Long = 37.9062f,
                            Name = "Kenya",
                            Population = 53771300
                        },
                        new
                        {
                            Iso2 = "KR",
                            Iso3 = "KOR",
                            Lat = 35.907757f,
                            Long = 127.76692f,
                            Name = "Korea, South",
                            Population = 51269183
                        },
                        new
                        {
                            Iso2 = "XK",
                            Iso3 = "XKS",
                            Lat = 42.602634f,
                            Long = 20.902977f,
                            Name = "Kosovo",
                            Population = 1810366
                        },
                        new
                        {
                            Iso2 = "KW",
                            Iso3 = "KWT",
                            Lat = 29.31166f,
                            Long = 47.481766f,
                            Name = "Kuwait",
                            Population = 4270563
                        },
                        new
                        {
                            Iso2 = "KG",
                            Iso3 = "KGZ",
                            Lat = 41.20438f,
                            Long = 74.7661f,
                            Name = "Kyrgyzstan",
                            Population = 6524191
                        },
                        new
                        {
                            Iso2 = "LA",
                            Iso3 = "LAO",
                            Lat = 19.85627f,
                            Long = 102.4955f,
                            Name = "Laos",
                            Population = 7275556
                        },
                        new
                        {
                            Iso2 = "LV",
                            Iso3 = "LVA",
                            Lat = 56.8796f,
                            Long = 24.6032f,
                            Name = "Latvia",
                            Population = 1886202
                        },
                        new
                        {
                            Iso2 = "LB",
                            Iso3 = "LBN",
                            Lat = 33.8547f,
                            Long = 35.8623f,
                            Name = "Lebanon",
                            Population = 6825442
                        },
                        new
                        {
                            Iso2 = "LR",
                            Iso3 = "LBR",
                            Lat = 6.428055f,
                            Long = -9.429499f,
                            Name = "Liberia",
                            Population = 5057677
                        },
                        new
                        {
                            Iso2 = "LY",
                            Iso3 = "LBY",
                            Lat = 26.3351f,
                            Long = 17.22833f,
                            Name = "Libya",
                            Population = 6871287
                        },
                        new
                        {
                            Iso2 = "LI",
                            Iso3 = "LIE",
                            Lat = 47.14f,
                            Long = 9.55f,
                            Name = "Liechtenstein",
                            Population = 38137
                        },
                        new
                        {
                            Iso2 = "LT",
                            Iso3 = "LTU",
                            Lat = 55.1694f,
                            Long = 23.8813f,
                            Name = "Lithuania",
                            Population = 2722291
                        },
                        new
                        {
                            Iso2 = "LU",
                            Iso3 = "LUX",
                            Lat = 49.8153f,
                            Long = 6.1296f,
                            Name = "Luxembourg",
                            Population = 625976
                        },
                        new
                        {
                            Iso2 = "MG",
                            Iso3 = "MDG",
                            Lat = -18.766947f,
                            Long = 46.869106f,
                            Name = "Madagascar",
                            Population = 27691019
                        },
                        new
                        {
                            Iso2 = "MW",
                            Iso3 = "MWI",
                            Lat = -13.2543f,
                            Long = 34.3015f,
                            Name = "Malawi",
                            Population = 19129955
                        },
                        new
                        {
                            Iso2 = "MY",
                            Iso3 = "MYS",
                            Lat = 4.210484f,
                            Long = 101.97577f,
                            Name = "Malaysia",
                            Population = 32365998
                        },
                        new
                        {
                            Iso2 = "MV",
                            Iso3 = "MDV",
                            Lat = 3.2028f,
                            Long = 73.2207f,
                            Name = "Maldives",
                            Population = 540542
                        },
                        new
                        {
                            Iso2 = "ML",
                            Iso3 = "MLI",
                            Lat = 17.570692f,
                            Long = -3.996166f,
                            Name = "Mali",
                            Population = 20250834
                        },
                        new
                        {
                            Iso2 = "MT",
                            Iso3 = "MLT",
                            Lat = 35.9375f,
                            Long = 14.3754f,
                            Name = "Malta",
                            Population = 441539
                        },
                        new
                        {
                            Iso2 = "MR",
                            Iso3 = "MRT",
                            Lat = 21.0079f,
                            Long = -10.9408f,
                            Name = "Mauritania",
                            Population = 4649660
                        },
                        new
                        {
                            Iso2 = "MU",
                            Iso3 = "MUS",
                            Lat = -20.348404f,
                            Long = 57.55215f,
                            Name = "Mauritius",
                            Population = 1271767
                        },
                        new
                        {
                            Iso2 = "MX",
                            Iso3 = "MEX",
                            Lat = 23.6345f,
                            Long = -102.5528f,
                            Name = "Mexico",
                            Population = 128932753
                        },
                        new
                        {
                            Iso2 = "MD",
                            Iso3 = "MDA",
                            Lat = 47.4116f,
                            Long = 28.3699f,
                            Name = "Moldova",
                            Population = 4033963
                        },
                        new
                        {
                            Iso2 = "MC",
                            Iso3 = "MCO",
                            Lat = 43.7333f,
                            Long = 7.4167f,
                            Name = "Monaco",
                            Population = 39244
                        },
                        new
                        {
                            Iso2 = "MN",
                            Iso3 = "MNG",
                            Lat = 46.8625f,
                            Long = 103.8467f,
                            Name = "Mongolia",
                            Population = 3278292
                        },
                        new
                        {
                            Iso2 = "ME",
                            Iso3 = "MNE",
                            Lat = 42.70868f,
                            Long = 19.37439f,
                            Name = "Montenegro",
                            Population = 628062
                        },
                        new
                        {
                            Iso2 = "MA",
                            Iso3 = "MAR",
                            Lat = 31.7917f,
                            Long = -7.0926f,
                            Name = "Morocco",
                            Population = 36910558
                        },
                        new
                        {
                            Iso2 = "MZ",
                            Iso3 = "MOZ",
                            Lat = -18.665695f,
                            Long = 35.529564f,
                            Name = "Mozambique",
                            Population = 31255435
                        },
                        new
                        {
                            Iso2 = "NA",
                            Iso3 = "NAM",
                            Lat = -22.9576f,
                            Long = 18.4904f,
                            Name = "Namibia",
                            Population = 2540916
                        },
                        new
                        {
                            Iso2 = "NP",
                            Iso3 = "NPL",
                            Lat = 28.1667f,
                            Long = 84.25f,
                            Name = "Nepal",
                            Population = 29136808
                        },
                        new
                        {
                            Iso2 = "NL",
                            Iso3 = "NLD",
                            Lat = 52.1326f,
                            Long = 5.2913f,
                            Name = "Netherlands",
                            Population = 17134873
                        },
                        new
                        {
                            Iso2 = "NZ",
                            Iso3 = "NZL",
                            Lat = -40.9006f,
                            Long = 174.886f,
                            Name = "New Zealand",
                            Population = 4822233
                        },
                        new
                        {
                            Iso2 = "NI",
                            Iso3 = "NIC",
                            Lat = 12.865416f,
                            Long = -85.20723f,
                            Name = "Nicaragua",
                            Population = 6624554
                        },
                        new
                        {
                            Iso2 = "NE",
                            Iso3 = "NER",
                            Lat = 17.607788f,
                            Long = 8.081666f,
                            Name = "Niger",
                            Population = 24206636
                        },
                        new
                        {
                            Iso2 = "NG",
                            Iso3 = "NGA",
                            Lat = 9.082f,
                            Long = 8.6753f,
                            Name = "Nigeria",
                            Population = 206139587
                        },
                        new
                        {
                            Iso2 = "MK",
                            Iso3 = "MKD",
                            Lat = 41.6086f,
                            Long = 21.7453f,
                            Name = "North Macedonia",
                            Population = 2083380
                        },
                        new
                        {
                            Iso2 = "NO",
                            Iso3 = "NOR",
                            Lat = 60.472f,
                            Long = 8.4689f,
                            Name = "Norway",
                            Population = 5421242
                        },
                        new
                        {
                            Iso2 = "OM",
                            Iso3 = "OMN",
                            Lat = 21.512583f,
                            Long = 55.923256f,
                            Name = "Oman",
                            Population = 5106622
                        },
                        new
                        {
                            Iso2 = "PK",
                            Iso3 = "PAK",
                            Lat = 30.3753f,
                            Long = 69.3451f,
                            Name = "Pakistan",
                            Population = 220892331
                        },
                        new
                        {
                            Iso2 = "PA",
                            Iso3 = "PAN",
                            Lat = 8.538f,
                            Long = -80.7821f,
                            Name = "Panama",
                            Population = 4314768
                        },
                        new
                        {
                            Iso2 = "PG",
                            Iso3 = "PNG",
                            Lat = -6.314993f,
                            Long = 143.95555f,
                            Name = "Papua New Guinea",
                            Population = 8947027
                        },
                        new
                        {
                            Iso2 = "PY",
                            Iso3 = "PRY",
                            Lat = -23.4425f,
                            Long = -58.4438f,
                            Name = "Paraguay",
                            Population = 7132530
                        },
                        new
                        {
                            Iso2 = "PE",
                            Iso3 = "PER",
                            Lat = -9.19f,
                            Long = -75.0152f,
                            Name = "Peru",
                            Population = 32971846
                        },
                        new
                        {
                            Iso2 = "PH",
                            Iso3 = "PHL",
                            Lat = 12.879721f,
                            Long = 121.77402f,
                            Name = "Philippines",
                            Population = 109581085
                        },
                        new
                        {
                            Iso2 = "PL",
                            Iso3 = "POL",
                            Lat = 51.9194f,
                            Long = 19.1451f,
                            Name = "Poland",
                            Population = 37846605
                        },
                        new
                        {
                            Iso2 = "PT",
                            Iso3 = "PRT",
                            Lat = 39.3999f,
                            Long = -8.2245f,
                            Name = "Portugal",
                            Population = 10196707
                        },
                        new
                        {
                            Iso2 = "QA",
                            Iso3 = "QAT",
                            Lat = 25.3548f,
                            Long = 51.1839f,
                            Name = "Qatar",
                            Population = 2881060
                        },
                        new
                        {
                            Iso2 = "RO",
                            Iso3 = "ROU",
                            Lat = 45.9432f,
                            Long = 24.9668f,
                            Name = "Romania",
                            Population = 19237682
                        },
                        new
                        {
                            Iso2 = "RU",
                            Iso3 = "RUS",
                            Lat = 61.52401f,
                            Long = 105.318756f,
                            Name = "Russia",
                            Population = 145934460
                        },
                        new
                        {
                            Iso2 = "RW",
                            Iso3 = "RWA",
                            Lat = -1.9403f,
                            Long = 29.8739f,
                            Name = "Rwanda",
                            Population = 12952209
                        },
                        new
                        {
                            Iso2 = "KN",
                            Iso3 = "KNA",
                            Lat = 17.357822f,
                            Long = -62.782997f,
                            Name = "Saint Kitts and Nevis",
                            Population = 53192
                        },
                        new
                        {
                            Iso2 = "LC",
                            Iso3 = "LCA",
                            Lat = 13.9094f,
                            Long = -60.9789f,
                            Name = "Saint Lucia",
                            Population = 183629
                        },
                        new
                        {
                            Iso2 = "VC",
                            Iso3 = "VCT",
                            Lat = 12.9843f,
                            Long = -61.2872f,
                            Name = "Saint Vincent and the Grenadines",
                            Population = 110947
                        },
                        new
                        {
                            Iso2 = "SM",
                            Iso3 = "SMR",
                            Lat = 43.9424f,
                            Long = 12.4578f,
                            Name = "San Marino",
                            Population = 33938
                        },
                        new
                        {
                            Iso2 = "ST",
                            Iso3 = "STP",
                            Lat = 0.1864f,
                            Long = 6.6131f,
                            Name = "Sao Tome and Principe",
                            Population = 219161
                        },
                        new
                        {
                            Iso2 = "SA",
                            Iso3 = "SAU",
                            Lat = 23.885942f,
                            Long = 45.079163f,
                            Name = "Saudi Arabia",
                            Population = 34813867
                        },
                        new
                        {
                            Iso2 = "SN",
                            Iso3 = "SEN",
                            Lat = 14.4974f,
                            Long = -14.4524f,
                            Name = "Senegal",
                            Population = 16743930
                        },
                        new
                        {
                            Iso2 = "RS",
                            Iso3 = "SRB",
                            Lat = 44.0165f,
                            Long = 21.0059f,
                            Name = "Serbia",
                            Population = 8737370
                        },
                        new
                        {
                            Iso2 = "SC",
                            Iso3 = "SYC",
                            Lat = -4.6796f,
                            Long = 55.492f,
                            Name = "Seychelles",
                            Population = 98340
                        },
                        new
                        {
                            Iso2 = "SL",
                            Iso3 = "SLE",
                            Lat = 8.460555f,
                            Long = -11.779889f,
                            Name = "Sierra Leone",
                            Population = 7976985
                        },
                        new
                        {
                            Iso2 = "SG",
                            Iso3 = "SGP",
                            Lat = 1.2833f,
                            Long = 103.8333f,
                            Name = "Singapore",
                            Population = 5850343
                        },
                        new
                        {
                            Iso2 = "SK",
                            Iso3 = "SVK",
                            Lat = 48.669f,
                            Long = 19.699f,
                            Name = "Slovakia",
                            Population = 5459643
                        },
                        new
                        {
                            Iso2 = "SI",
                            Iso3 = "SVN",
                            Lat = 46.1512f,
                            Long = 14.9955f,
                            Name = "Slovenia",
                            Population = 2078932
                        },
                        new
                        {
                            Iso2 = "SO",
                            Iso3 = "SOM",
                            Lat = 5.152149f,
                            Long = 46.199615f,
                            Name = "Somalia",
                            Population = 15893219
                        },
                        new
                        {
                            Iso2 = "ZA",
                            Iso3 = "ZAF",
                            Lat = -30.5595f,
                            Long = 22.9375f,
                            Name = "South Africa",
                            Population = 59308690
                        },
                        new
                        {
                            Iso2 = "SS",
                            Iso3 = "SSD",
                            Lat = 6.877f,
                            Long = 31.307f,
                            Name = "South Sudan",
                            Population = 11193729
                        },
                        new
                        {
                            Iso2 = "ES",
                            Iso3 = "ESP",
                            Lat = 40.46367f,
                            Long = -3.74922f,
                            Name = "Spain",
                            Population = 46754783
                        },
                        new
                        {
                            Iso2 = "LK",
                            Iso3 = "LKA",
                            Lat = 7.873054f,
                            Long = 80.7718f,
                            Name = "Sri Lanka",
                            Population = 21413250
                        },
                        new
                        {
                            Iso2 = "SD",
                            Iso3 = "SDN",
                            Lat = 12.8628f,
                            Long = 30.2176f,
                            Name = "Sudan",
                            Population = 43849269
                        },
                        new
                        {
                            Iso2 = "SR",
                            Iso3 = "SUR",
                            Lat = 3.9193f,
                            Long = -56.0278f,
                            Name = "Suriname",
                            Population = 586634
                        },
                        new
                        {
                            Iso2 = "SE",
                            Iso3 = "SWE",
                            Lat = 60.128162f,
                            Long = 18.643501f,
                            Name = "Sweden",
                            Population = 10099270
                        },
                        new
                        {
                            Iso2 = "CH",
                            Iso3 = "CHE",
                            Lat = 46.8182f,
                            Long = 8.2275f,
                            Name = "Switzerland",
                            Population = 8654618
                        },
                        new
                        {
                            Iso2 = "SY",
                            Iso3 = "SYR",
                            Lat = 34.802074f,
                            Long = 38.996815f,
                            Name = "Syria",
                            Population = 17500657
                        },
                        new
                        {
                            Iso2 = "TW",
                            Iso3 = "TWN",
                            Lat = 23.7f,
                            Long = 121f,
                            Name = "Taiwan*",
                            Population = 23816775
                        },
                        new
                        {
                            Iso2 = "TZ",
                            Iso3 = "TZA",
                            Lat = -6.369028f,
                            Long = 34.88882f,
                            Name = "Tanzania",
                            Population = 59734213
                        },
                        new
                        {
                            Iso2 = "TH",
                            Iso3 = "THA",
                            Lat = 15.870032f,
                            Long = 100.99254f,
                            Name = "Thailand",
                            Population = 69799978
                        },
                        new
                        {
                            Iso2 = "TL",
                            Iso3 = "TLS",
                            Lat = -8.874217f,
                            Long = 125.72754f,
                            Name = "Timor-Leste",
                            Population = 1318442
                        },
                        new
                        {
                            Iso2 = "TG",
                            Iso3 = "TGO",
                            Lat = 8.6195f,
                            Long = 0.8248f,
                            Name = "Togo",
                            Population = 8278737
                        },
                        new
                        {
                            Iso2 = "TT",
                            Iso3 = "TTO",
                            Lat = 10.6918f,
                            Long = -61.2225f,
                            Name = "Trinidad and Tobago",
                            Population = 1399491
                        },
                        new
                        {
                            Iso2 = "TN",
                            Iso3 = "TUN",
                            Lat = 33.886917f,
                            Long = 9.537499f,
                            Name = "Tunisia",
                            Population = 11818618
                        },
                        new
                        {
                            Iso2 = "TR",
                            Iso3 = "TUR",
                            Lat = 38.9637f,
                            Long = 35.2433f,
                            Name = "Turkey",
                            Population = 84339067
                        },
                        new
                        {
                            Iso2 = "UG",
                            Iso3 = "UGA",
                            Lat = 1.373333f,
                            Long = 32.290276f,
                            Name = "Uganda",
                            Population = 45741000
                        },
                        new
                        {
                            Iso2 = "UA",
                            Iso3 = "UKR",
                            Lat = 48.3794f,
                            Long = 31.1656f,
                            Name = "Ukraine",
                            Population = 43733759
                        },
                        new
                        {
                            Iso2 = "AE",
                            Iso3 = "ARE",
                            Lat = 23.424076f,
                            Long = 53.847816f,
                            Name = "United Arab Emirates",
                            Population = 9890400
                        },
                        new
                        {
                            Iso2 = "GB",
                            Iso3 = "GBR",
                            Lat = 55.3781f,
                            Long = -3.436f,
                            Name = "United Kingdom",
                            Population = 67886004
                        },
                        new
                        {
                            Iso2 = "UY",
                            Iso3 = "URY",
                            Lat = -32.5228f,
                            Long = -55.7658f,
                            Name = "Uruguay",
                            Population = 3473727
                        },
                        new
                        {
                            Iso2 = "UZ",
                            Iso3 = "UZB",
                            Lat = 41.37749f,
                            Long = 64.58526f,
                            Name = "Uzbekistan",
                            Population = 33469199
                        },
                        new
                        {
                            Iso2 = "VE",
                            Iso3 = "VEN",
                            Lat = 6.4238f,
                            Long = -66.5897f,
                            Name = "Venezuela",
                            Population = 28435943
                        },
                        new
                        {
                            Iso2 = "VN",
                            Iso3 = "VNM",
                            Lat = 14.058324f,
                            Long = 108.2772f,
                            Name = "Vietnam",
                            Population = 97338583
                        },
                        new
                        {
                            Iso2 = "PS",
                            Iso3 = "PSE",
                            Lat = 31.9522f,
                            Long = 35.2332f,
                            Name = "West Bank and Gaza",
                            Population = 5101416
                        },
                        new
                        {
                            Iso2 = "EH",
                            Iso3 = "ESH",
                            Lat = 24.2155f,
                            Long = -12.8858f,
                            Name = "Western Sahara",
                            Population = 597330
                        },
                        new
                        {
                            Iso2 = "YE",
                            Iso3 = "YEM",
                            Lat = 15.552727f,
                            Long = 48.516388f,
                            Name = "Yemen",
                            Population = 29825968
                        },
                        new
                        {
                            Iso2 = "ZM",
                            Iso3 = "ZMB",
                            Lat = -13.133897f,
                            Long = 27.849333f,
                            Name = "Zambia",
                            Population = 18383956
                        },
                        new
                        {
                            Iso2 = "ZW",
                            Iso3 = "ZWE",
                            Lat = -19.015438f,
                            Long = 29.154858f,
                            Name = "Zimbabwe",
                            Population = 14862927
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
